/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace IERC8004Reputation {
  export type FeedbackStruct = {
    clientAddress: AddressLike;
    value: BigNumberish;
    valueDecimals: BigNumberish;
    tag1: string;
    tag2: string;
    endpointURI: string;
    fileURI: string;
    fileHash: BytesLike;
    timestamp: BigNumberish;
  };

  export type FeedbackStructOutput = [
    clientAddress: string,
    value: bigint,
    valueDecimals: bigint,
    tag1: string,
    tag2: string,
    endpointURI: string,
    fileURI: string,
    fileHash: string,
    timestamp: bigint
  ] & {
    clientAddress: string;
    value: bigint;
    valueDecimals: bigint;
    tag1: string;
    tag2: string;
    endpointURI: string;
    fileURI: string;
    fileHash: string;
    timestamp: bigint;
  };
}

export interface IERC8004ReputationInterface extends Interface {
  getFunction(
    nameOrSignature: "getSummary" | "giveFeedback" | "readAllFeedback"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getSummary",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "giveFeedback",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      string,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "readAllFeedback",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getSummary", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "giveFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "readAllFeedback",
    data: BytesLike
  ): Result;
}

export interface IERC8004Reputation extends BaseContract {
  connect(runner?: ContractRunner | null): IERC8004Reputation;
  waitForDeployment(): Promise<this>;

  interface: IERC8004ReputationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getSummary: TypedContractMethod<
    [agentId: BigNumberish],
    [[bigint, bigint] & { feedbackCount: bigint; averageValue: bigint }],
    "view"
  >;

  giveFeedback: TypedContractMethod<
    [
      agentId: BigNumberish,
      value: BigNumberish,
      valueDecimals: BigNumberish,
      tag1: string,
      tag2: string,
      endpointURI: string,
      fileURI: string,
      fileHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  readAllFeedback: TypedContractMethod<
    [agentId: BigNumberish],
    [IERC8004Reputation.FeedbackStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getSummary"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [[bigint, bigint] & { feedbackCount: bigint; averageValue: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "giveFeedback"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      value: BigNumberish,
      valueDecimals: BigNumberish,
      tag1: string,
      tag2: string,
      endpointURI: string,
      fileURI: string,
      fileHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "readAllFeedback"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [IERC8004Reputation.FeedbackStructOutput[]],
    "view"
  >;

  filters: {};
}
