/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IERC8004IdentityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ownerOf"
      | "register"
      | "setAgentURI"
      | "setAgentWallet"
      | "tokenURI"
      | "totalSupply"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "AgentURIUpdated"
      | "AgentWalletUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "register", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setAgentURI",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentWallet",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAgentURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    owner: AddressLike,
    agentURI: string
  ];
  export type OutputTuple = [agentId: bigint, owner: string, agentURI: string];
  export interface OutputObject {
    agentId: bigint;
    owner: string;
    agentURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentURIUpdatedEvent {
  export type InputTuple = [agentId: BigNumberish, agentURI: string];
  export type OutputTuple = [agentId: bigint, agentURI: string];
  export interface OutputObject {
    agentId: bigint;
    agentURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentWalletUpdatedEvent {
  export type InputTuple = [agentId: BigNumberish, wallet: AddressLike];
  export type OutputTuple = [agentId: bigint, wallet: string];
  export interface OutputObject {
    agentId: bigint;
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IERC8004Identity extends BaseContract {
  connect(runner?: ContractRunner | null): IERC8004Identity;
  waitForDeployment(): Promise<this>;

  interface: IERC8004IdentityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ownerOf: TypedContractMethod<[agentId: BigNumberish], [string], "view">;

  register: TypedContractMethod<[agentURI: string], [bigint], "nonpayable">;

  setAgentURI: TypedContractMethod<
    [agentId: BigNumberish, agentURI: string],
    [void],
    "nonpayable"
  >;

  setAgentWallet: TypedContractMethod<
    [
      agentId: BigNumberish,
      wallet: AddressLike,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  tokenURI: TypedContractMethod<[agentId: BigNumberish], [string], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[agentId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[agentURI: string], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "setAgentURI"
  ): TypedContractMethod<
    [agentId: BigNumberish, agentURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgentWallet"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      wallet: AddressLike,
      deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[agentId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentURIUpdated"
  ): TypedContractEvent<
    AgentURIUpdatedEvent.InputTuple,
    AgentURIUpdatedEvent.OutputTuple,
    AgentURIUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentWalletUpdated"
  ): TypedContractEvent<
    AgentWalletUpdatedEvent.InputTuple,
    AgentWalletUpdatedEvent.OutputTuple,
    AgentWalletUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(uint256,address,string)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentURIUpdated(uint256,string)": TypedContractEvent<
      AgentURIUpdatedEvent.InputTuple,
      AgentURIUpdatedEvent.OutputTuple,
      AgentURIUpdatedEvent.OutputObject
    >;
    AgentURIUpdated: TypedContractEvent<
      AgentURIUpdatedEvent.InputTuple,
      AgentURIUpdatedEvent.OutputTuple,
      AgentURIUpdatedEvent.OutputObject
    >;

    "AgentWalletUpdated(uint256,address)": TypedContractEvent<
      AgentWalletUpdatedEvent.InputTuple,
      AgentWalletUpdatedEvent.OutputTuple,
      AgentWalletUpdatedEvent.OutputObject
    >;
    AgentWalletUpdated: TypedContractEvent<
      AgentWalletUpdatedEvent.InputTuple,
      AgentWalletUpdatedEvent.OutputTuple,
      AgentWalletUpdatedEvent.OutputObject
    >;
  };
}
