/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAttestationLoggerInterface extends Interface {
  getFunction(
    nameOrSignature: "logAgentAction" | "logPayment"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "logAgentAction",
    values: [BytesLike, BytesLike, string, BytesLike, BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "logPayment",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      AddressLike,
      BigNumberish,
      AddressLike,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "logAgentAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "logPayment", data: BytesLike): Result;
}

export interface IAttestationLogger extends BaseContract {
  connect(runner?: ContractRunner | null): IAttestationLogger;
  waitForDeployment(): Promise<this>;

  interface: IAttestationLoggerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  logAgentAction: TypedContractMethod<
    [
      paymentId: BytesLike,
      agentId: BytesLike,
      action: string,
      inputHash: BytesLike,
      outputHash: BytesLike,
      success: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  logPayment: TypedContractMethod<
    [
      paymentId: BytesLike,
      business: AddressLike,
      recipient: AddressLike,
      amountIn: BigNumberish,
      tokenIn: AddressLike,
      amountOut: BigNumberish,
      tokenOut: AddressLike,
      agentId: BytesLike,
      stateHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "logAgentAction"
  ): TypedContractMethod<
    [
      paymentId: BytesLike,
      agentId: BytesLike,
      action: string,
      inputHash: BytesLike,
      outputHash: BytesLike,
      success: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logPayment"
  ): TypedContractMethod<
    [
      paymentId: BytesLike,
      business: AddressLike,
      recipient: AddressLike,
      amountIn: BigNumberish,
      tokenIn: AddressLike,
      amountOut: BigNumberish,
      tokenOut: AddressLike,
      agentId: BytesLike,
      stateHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
