/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace PaymentOrchestrator {
  export type PaymentRecordStruct = {
    id: BytesLike;
    business: AddressLike;
    recipient: AddressLike;
    amountIn: BigNumberish;
    tokenIn: AddressLike;
    amountOut: BigNumberish;
    tokenOut: AddressLike;
    status: BigNumberish;
    timestamp: BigNumberish;
    attestationId: BigNumberish;
    agentId: BytesLike;
  };

  export type PaymentRecordStructOutput = [
    id: string,
    business: string,
    recipient: string,
    amountIn: bigint,
    tokenIn: string,
    amountOut: bigint,
    tokenOut: string,
    status: bigint,
    timestamp: bigint,
    attestationId: bigint,
    agentId: string
  ] & {
    id: string;
    business: string;
    recipient: string;
    amountIn: bigint;
    tokenIn: string;
    amountOut: bigint;
    tokenOut: string;
    status: bigint;
    timestamp: bigint;
    attestationId: bigint;
    agentId: string;
  };
}

export interface PaymentOrchestratorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attestationLogger"
      | "authorizeAgent"
      | "authorizedAgents"
      | "executeDirectPayment"
      | "executeFXPayment"
      | "getPayment"
      | "mentoBroker"
      | "owner"
      | "payments"
      | "policyEngine"
      | "quoteFX"
      | "renounceOwnership"
      | "revokeAgent"
      | "setAttestationLogger"
      | "setBroker"
      | "setPolicyEngine"
      | "totalPaymentsExecuted"
      | "totalVolumeUSD"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentAuthorized"
      | "AgentRevoked"
      | "AttestationLoggerUpdated"
      | "BrokerUpdated"
      | "OwnershipTransferred"
      | "PaymentExecuted"
      | "PaymentFailed"
      | "PaymentInitiated"
      | "PolicyEngineUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "attestationLogger",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeAgent",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedAgents",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeDirectPayment",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      AddressLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeFXPayment",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mentoBroker",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "payments", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "policyEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "quoteFX",
    values: [AddressLike, BytesLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAttestationLogger",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBroker",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPolicyEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPaymentsExecuted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVolumeUSD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "attestationLogger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeDirectPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeFXPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPayment", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mentoBroker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payments", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "policyEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "quoteFX", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAttestationLogger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBroker", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPolicyEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPaymentsExecuted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVolumeUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AgentAuthorizedEvent {
  export type InputTuple = [agent: AddressLike, agentId: BytesLike];
  export type OutputTuple = [agent: string, agentId: string];
  export interface OutputObject {
    agent: string;
    agentId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRevokedEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttestationLoggerUpdatedEvent {
  export type InputTuple = [newLogger: AddressLike];
  export type OutputTuple = [newLogger: string];
  export interface OutputObject {
    newLogger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BrokerUpdatedEvent {
  export type InputTuple = [newBroker: AddressLike];
  export type OutputTuple = [newBroker: string];
  export interface OutputObject {
    newBroker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentExecutedEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    amountOut: BigNumberish,
    tokenOut: AddressLike,
    agentId: BytesLike
  ];
  export type OutputTuple = [
    paymentId: string,
    amountOut: bigint,
    tokenOut: string,
    agentId: string
  ];
  export interface OutputObject {
    paymentId: string;
    amountOut: bigint;
    tokenOut: string;
    agentId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentFailedEvent {
  export type InputTuple = [paymentId: BytesLike, reason: string];
  export type OutputTuple = [paymentId: string, reason: string];
  export interface OutputObject {
    paymentId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentInitiatedEvent {
  export type InputTuple = [
    paymentId: BytesLike,
    business: AddressLike,
    recipient: AddressLike,
    amountIn: BigNumberish,
    tokenIn: AddressLike
  ];
  export type OutputTuple = [
    paymentId: string,
    business: string,
    recipient: string,
    amountIn: bigint,
    tokenIn: string
  ];
  export interface OutputObject {
    paymentId: string;
    business: string;
    recipient: string;
    amountIn: bigint;
    tokenIn: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyEngineUpdatedEvent {
  export type InputTuple = [newEngine: AddressLike];
  export type OutputTuple = [newEngine: string];
  export interface OutputObject {
    newEngine: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PaymentOrchestrator extends BaseContract {
  connect(runner?: ContractRunner | null): PaymentOrchestrator;
  waitForDeployment(): Promise<this>;

  interface: PaymentOrchestratorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attestationLogger: TypedContractMethod<[], [string], "view">;

  authorizeAgent: TypedContractMethod<
    [agent: AddressLike, agentId: BytesLike],
    [void],
    "nonpayable"
  >;

  authorizedAgents: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  executeDirectPayment: TypedContractMethod<
    [
      paymentId: BytesLike,
      business: AddressLike,
      recipient: AddressLike,
      amount: BigNumberish,
      token: AddressLike,
      agentId: BytesLike,
      stateHash: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  executeFXPayment: TypedContractMethod<
    [
      paymentId: BytesLike,
      business: AddressLike,
      recipient: AddressLike,
      amountIn: BigNumberish,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      exchangeProvider: AddressLike,
      exchangeId: BytesLike,
      minAmountOut: BigNumberish,
      agentId: BytesLike,
      stateHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getPayment: TypedContractMethod<
    [paymentId: BytesLike],
    [PaymentOrchestrator.PaymentRecordStructOutput],
    "view"
  >;

  mentoBroker: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  payments: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        id: string;
        business: string;
        recipient: string;
        amountIn: bigint;
        tokenIn: string;
        amountOut: bigint;
        tokenOut: string;
        status: bigint;
        timestamp: bigint;
        attestationId: bigint;
        agentId: string;
      }
    ],
    "view"
  >;

  policyEngine: TypedContractMethod<[], [string], "view">;

  quoteFX: TypedContractMethod<
    [
      exchangeProvider: AddressLike,
      exchangeId: BytesLike,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish
    ],
    [bigint],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeAgent: TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;

  setAttestationLogger: TypedContractMethod<
    [_logger: AddressLike],
    [void],
    "nonpayable"
  >;

  setBroker: TypedContractMethod<[_broker: AddressLike], [void], "nonpayable">;

  setPolicyEngine: TypedContractMethod<
    [_policyEngine: AddressLike],
    [void],
    "nonpayable"
  >;

  totalPaymentsExecuted: TypedContractMethod<[], [bigint], "view">;

  totalVolumeUSD: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attestationLogger"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "authorizeAgent"
  ): TypedContractMethod<
    [agent: AddressLike, agentId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedAgents"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "executeDirectPayment"
  ): TypedContractMethod<
    [
      paymentId: BytesLike,
      business: AddressLike,
      recipient: AddressLike,
      amount: BigNumberish,
      token: AddressLike,
      agentId: BytesLike,
      stateHash: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeFXPayment"
  ): TypedContractMethod<
    [
      paymentId: BytesLike,
      business: AddressLike,
      recipient: AddressLike,
      amountIn: BigNumberish,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      exchangeProvider: AddressLike,
      exchangeId: BytesLike,
      minAmountOut: BigNumberish,
      agentId: BytesLike,
      stateHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPayment"
  ): TypedContractMethod<
    [paymentId: BytesLike],
    [PaymentOrchestrator.PaymentRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "mentoBroker"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payments"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        id: string;
        business: string;
        recipient: string;
        amountIn: bigint;
        tokenIn: string;
        amountOut: bigint;
        tokenOut: string;
        status: bigint;
        timestamp: bigint;
        attestationId: bigint;
        agentId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "policyEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quoteFX"
  ): TypedContractMethod<
    [
      exchangeProvider: AddressLike,
      exchangeId: BytesLike,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeAgent"
  ): TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAttestationLogger"
  ): TypedContractMethod<[_logger: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBroker"
  ): TypedContractMethod<[_broker: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPolicyEngine"
  ): TypedContractMethod<[_policyEngine: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalPaymentsExecuted"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVolumeUSD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AgentAuthorized"
  ): TypedContractEvent<
    AgentAuthorizedEvent.InputTuple,
    AgentAuthorizedEvent.OutputTuple,
    AgentAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRevoked"
  ): TypedContractEvent<
    AgentRevokedEvent.InputTuple,
    AgentRevokedEvent.OutputTuple,
    AgentRevokedEvent.OutputObject
  >;
  getEvent(
    key: "AttestationLoggerUpdated"
  ): TypedContractEvent<
    AttestationLoggerUpdatedEvent.InputTuple,
    AttestationLoggerUpdatedEvent.OutputTuple,
    AttestationLoggerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BrokerUpdated"
  ): TypedContractEvent<
    BrokerUpdatedEvent.InputTuple,
    BrokerUpdatedEvent.OutputTuple,
    BrokerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentExecuted"
  ): TypedContractEvent<
    PaymentExecutedEvent.InputTuple,
    PaymentExecutedEvent.OutputTuple,
    PaymentExecutedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentFailed"
  ): TypedContractEvent<
    PaymentFailedEvent.InputTuple,
    PaymentFailedEvent.OutputTuple,
    PaymentFailedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentInitiated"
  ): TypedContractEvent<
    PaymentInitiatedEvent.InputTuple,
    PaymentInitiatedEvent.OutputTuple,
    PaymentInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyEngineUpdated"
  ): TypedContractEvent<
    PolicyEngineUpdatedEvent.InputTuple,
    PolicyEngineUpdatedEvent.OutputTuple,
    PolicyEngineUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentAuthorized(address,bytes32)": TypedContractEvent<
      AgentAuthorizedEvent.InputTuple,
      AgentAuthorizedEvent.OutputTuple,
      AgentAuthorizedEvent.OutputObject
    >;
    AgentAuthorized: TypedContractEvent<
      AgentAuthorizedEvent.InputTuple,
      AgentAuthorizedEvent.OutputTuple,
      AgentAuthorizedEvent.OutputObject
    >;

    "AgentRevoked(address)": TypedContractEvent<
      AgentRevokedEvent.InputTuple,
      AgentRevokedEvent.OutputTuple,
      AgentRevokedEvent.OutputObject
    >;
    AgentRevoked: TypedContractEvent<
      AgentRevokedEvent.InputTuple,
      AgentRevokedEvent.OutputTuple,
      AgentRevokedEvent.OutputObject
    >;

    "AttestationLoggerUpdated(address)": TypedContractEvent<
      AttestationLoggerUpdatedEvent.InputTuple,
      AttestationLoggerUpdatedEvent.OutputTuple,
      AttestationLoggerUpdatedEvent.OutputObject
    >;
    AttestationLoggerUpdated: TypedContractEvent<
      AttestationLoggerUpdatedEvent.InputTuple,
      AttestationLoggerUpdatedEvent.OutputTuple,
      AttestationLoggerUpdatedEvent.OutputObject
    >;

    "BrokerUpdated(address)": TypedContractEvent<
      BrokerUpdatedEvent.InputTuple,
      BrokerUpdatedEvent.OutputTuple,
      BrokerUpdatedEvent.OutputObject
    >;
    BrokerUpdated: TypedContractEvent<
      BrokerUpdatedEvent.InputTuple,
      BrokerUpdatedEvent.OutputTuple,
      BrokerUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentExecuted(bytes32,uint256,address,bytes32)": TypedContractEvent<
      PaymentExecutedEvent.InputTuple,
      PaymentExecutedEvent.OutputTuple,
      PaymentExecutedEvent.OutputObject
    >;
    PaymentExecuted: TypedContractEvent<
      PaymentExecutedEvent.InputTuple,
      PaymentExecutedEvent.OutputTuple,
      PaymentExecutedEvent.OutputObject
    >;

    "PaymentFailed(bytes32,string)": TypedContractEvent<
      PaymentFailedEvent.InputTuple,
      PaymentFailedEvent.OutputTuple,
      PaymentFailedEvent.OutputObject
    >;
    PaymentFailed: TypedContractEvent<
      PaymentFailedEvent.InputTuple,
      PaymentFailedEvent.OutputTuple,
      PaymentFailedEvent.OutputObject
    >;

    "PaymentInitiated(bytes32,address,address,uint256,address)": TypedContractEvent<
      PaymentInitiatedEvent.InputTuple,
      PaymentInitiatedEvent.OutputTuple,
      PaymentInitiatedEvent.OutputObject
    >;
    PaymentInitiated: TypedContractEvent<
      PaymentInitiatedEvent.InputTuple,
      PaymentInitiatedEvent.OutputTuple,
      PaymentInitiatedEvent.OutputObject
    >;

    "PolicyEngineUpdated(address)": TypedContractEvent<
      PolicyEngineUpdatedEvent.InputTuple,
      PolicyEngineUpdatedEvent.OutputTuple,
      PolicyEngineUpdatedEvent.OutputObject
    >;
    PolicyEngineUpdated: TypedContractEvent<
      PolicyEngineUpdatedEvent.InputTuple,
      PolicyEngineUpdatedEvent.OutputTuple,
      PolicyEngineUpdatedEvent.OutputObject
    >;
  };
}
