/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AttestationLogger {
  export type PaymentAttestationStruct = {
    id: BigNumberish;
    paymentId: BytesLike;
    business: AddressLike;
    recipient: AddressLike;
    amountIn: BigNumberish;
    tokenIn: AddressLike;
    amountOut: BigNumberish;
    tokenOut: AddressLike;
    agentId: BytesLike;
    timestamp: BigNumberish;
    stateHash: BytesLike;
  };

  export type PaymentAttestationStructOutput = [
    id: bigint,
    paymentId: string,
    business: string,
    recipient: string,
    amountIn: bigint,
    tokenIn: string,
    amountOut: bigint,
    tokenOut: string,
    agentId: string,
    timestamp: bigint,
    stateHash: string
  ] & {
    id: bigint;
    paymentId: string;
    business: string;
    recipient: string;
    amountIn: bigint;
    tokenIn: string;
    amountOut: bigint;
    tokenOut: string;
    agentId: string;
    timestamp: bigint;
    stateHash: string;
  };

  export type AgentActionLogStruct = {
    id: BigNumberish;
    paymentId: BytesLike;
    agentId: BytesLike;
    action: string;
    inputHash: BytesLike;
    outputHash: BytesLike;
    success: boolean;
    timestamp: BigNumberish;
  };

  export type AgentActionLogStructOutput = [
    id: bigint,
    paymentId: string,
    agentId: string,
    action: string,
    inputHash: string,
    outputHash: string,
    success: boolean,
    timestamp: bigint
  ] & {
    id: bigint;
    paymentId: string;
    agentId: string;
    action: string;
    inputHash: string;
    outputHash: string;
    success: boolean;
    timestamp: bigint;
  };
}

export interface AttestationLoggerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "actionLogCount"
      | "actionLogs"
      | "attestationCount"
      | "attestations"
      | "authorizeLogger"
      | "authorizedLoggers"
      | "getAttestation"
      | "getPaymentActions"
      | "getPaymentAttestation"
      | "getRecentAttestations"
      | "logAgentAction"
      | "logPayment"
      | "owner"
      | "paymentIdToActions"
      | "paymentIdToAttestation"
      | "renounceOwnership"
      | "revokeLogger"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentActionLogged"
      | "LoggerAuthorized"
      | "LoggerRevoked"
      | "OwnershipTransferred"
      | "PaymentAttested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "actionLogCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "actionLogs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "attestationCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "attestations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeLogger",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedLoggers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttestation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentActions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentAttestation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecentAttestations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "logAgentAction",
    values: [BytesLike, BytesLike, string, BytesLike, BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "logPayment",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      AddressLike,
      BigNumberish,
      AddressLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentIdToActions",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "paymentIdToAttestation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeLogger",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "actionLogCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "actionLogs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attestationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeLogger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedLoggers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentActions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecentAttestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logAgentAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "logPayment", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentIdToActions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "paymentIdToAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeLogger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AgentActionLoggedEvent {
  export type InputTuple = [
    id: BigNumberish,
    paymentId: BytesLike,
    agentId: BytesLike,
    action: string,
    success: boolean
  ];
  export type OutputTuple = [
    id: bigint,
    paymentId: string,
    agentId: string,
    action: string,
    success: boolean
  ];
  export interface OutputObject {
    id: bigint;
    paymentId: string;
    agentId: string;
    action: string;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoggerAuthorizedEvent {
  export type InputTuple = [logger: AddressLike];
  export type OutputTuple = [logger: string];
  export interface OutputObject {
    logger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoggerRevokedEvent {
  export type InputTuple = [logger: AddressLike];
  export type OutputTuple = [logger: string];
  export interface OutputObject {
    logger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentAttestedEvent {
  export type InputTuple = [
    id: BigNumberish,
    paymentId: BytesLike,
    business: AddressLike,
    recipient: AddressLike,
    amountIn: BigNumberish,
    tokenIn: AddressLike,
    amountOut: BigNumberish,
    tokenOut: AddressLike,
    agentId: BytesLike
  ];
  export type OutputTuple = [
    id: bigint,
    paymentId: string,
    business: string,
    recipient: string,
    amountIn: bigint,
    tokenIn: string,
    amountOut: bigint,
    tokenOut: string,
    agentId: string
  ];
  export interface OutputObject {
    id: bigint;
    paymentId: string;
    business: string;
    recipient: string;
    amountIn: bigint;
    tokenIn: string;
    amountOut: bigint;
    tokenOut: string;
    agentId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AttestationLogger extends BaseContract {
  connect(runner?: ContractRunner | null): AttestationLogger;
  waitForDeployment(): Promise<this>;

  interface: AttestationLoggerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  actionLogCount: TypedContractMethod<[], [bigint], "view">;

  actionLogs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, string, boolean, bigint] & {
        id: bigint;
        paymentId: string;
        agentId: string;
        action: string;
        inputHash: string;
        outputHash: string;
        success: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  attestationCount: TypedContractMethod<[], [bigint], "view">;

  attestations: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        string,
        string,
        bigint,
        string
      ] & {
        id: bigint;
        paymentId: string;
        business: string;
        recipient: string;
        amountIn: bigint;
        tokenIn: string;
        amountOut: bigint;
        tokenOut: string;
        agentId: string;
        timestamp: bigint;
        stateHash: string;
      }
    ],
    "view"
  >;

  authorizeLogger: TypedContractMethod<
    [logger: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedLoggers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getAttestation: TypedContractMethod<
    [id: BigNumberish],
    [AttestationLogger.PaymentAttestationStructOutput],
    "view"
  >;

  getPaymentActions: TypedContractMethod<
    [paymentId: BytesLike],
    [AttestationLogger.AgentActionLogStructOutput[]],
    "view"
  >;

  getPaymentAttestation: TypedContractMethod<
    [paymentId: BytesLike],
    [AttestationLogger.PaymentAttestationStructOutput],
    "view"
  >;

  getRecentAttestations: TypedContractMethod<
    [count: BigNumberish],
    [AttestationLogger.PaymentAttestationStructOutput[]],
    "view"
  >;

  logAgentAction: TypedContractMethod<
    [
      paymentId: BytesLike,
      agentId: BytesLike,
      action: string,
      inputHash: BytesLike,
      outputHash: BytesLike,
      success: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  logPayment: TypedContractMethod<
    [
      paymentId: BytesLike,
      business: AddressLike,
      recipient: AddressLike,
      amountIn: BigNumberish,
      tokenIn: AddressLike,
      amountOut: BigNumberish,
      tokenOut: AddressLike,
      agentId: BytesLike,
      stateHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  paymentIdToActions: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  paymentIdToAttestation: TypedContractMethod<
    [arg0: BytesLike],
    [bigint],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeLogger: TypedContractMethod<
    [logger: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "actionLogCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "actionLogs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, string, boolean, bigint] & {
        id: bigint;
        paymentId: string;
        agentId: string;
        action: string;
        inputHash: string;
        outputHash: string;
        success: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "attestationCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "attestations"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        string,
        string,
        bigint,
        string
      ] & {
        id: bigint;
        paymentId: string;
        business: string;
        recipient: string;
        amountIn: bigint;
        tokenIn: string;
        amountOut: bigint;
        tokenOut: string;
        agentId: string;
        timestamp: bigint;
        stateHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "authorizeLogger"
  ): TypedContractMethod<[logger: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedLoggers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAttestation"
  ): TypedContractMethod<
    [id: BigNumberish],
    [AttestationLogger.PaymentAttestationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPaymentActions"
  ): TypedContractMethod<
    [paymentId: BytesLike],
    [AttestationLogger.AgentActionLogStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPaymentAttestation"
  ): TypedContractMethod<
    [paymentId: BytesLike],
    [AttestationLogger.PaymentAttestationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecentAttestations"
  ): TypedContractMethod<
    [count: BigNumberish],
    [AttestationLogger.PaymentAttestationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "logAgentAction"
  ): TypedContractMethod<
    [
      paymentId: BytesLike,
      agentId: BytesLike,
      action: string,
      inputHash: BytesLike,
      outputHash: BytesLike,
      success: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logPayment"
  ): TypedContractMethod<
    [
      paymentId: BytesLike,
      business: AddressLike,
      recipient: AddressLike,
      amountIn: BigNumberish,
      tokenIn: AddressLike,
      amountOut: BigNumberish,
      tokenOut: AddressLike,
      agentId: BytesLike,
      stateHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentIdToActions"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "paymentIdToAttestation"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeLogger"
  ): TypedContractMethod<[logger: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AgentActionLogged"
  ): TypedContractEvent<
    AgentActionLoggedEvent.InputTuple,
    AgentActionLoggedEvent.OutputTuple,
    AgentActionLoggedEvent.OutputObject
  >;
  getEvent(
    key: "LoggerAuthorized"
  ): TypedContractEvent<
    LoggerAuthorizedEvent.InputTuple,
    LoggerAuthorizedEvent.OutputTuple,
    LoggerAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "LoggerRevoked"
  ): TypedContractEvent<
    LoggerRevokedEvent.InputTuple,
    LoggerRevokedEvent.OutputTuple,
    LoggerRevokedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentAttested"
  ): TypedContractEvent<
    PaymentAttestedEvent.InputTuple,
    PaymentAttestedEvent.OutputTuple,
    PaymentAttestedEvent.OutputObject
  >;

  filters: {
    "AgentActionLogged(uint256,bytes32,bytes32,string,bool)": TypedContractEvent<
      AgentActionLoggedEvent.InputTuple,
      AgentActionLoggedEvent.OutputTuple,
      AgentActionLoggedEvent.OutputObject
    >;
    AgentActionLogged: TypedContractEvent<
      AgentActionLoggedEvent.InputTuple,
      AgentActionLoggedEvent.OutputTuple,
      AgentActionLoggedEvent.OutputObject
    >;

    "LoggerAuthorized(address)": TypedContractEvent<
      LoggerAuthorizedEvent.InputTuple,
      LoggerAuthorizedEvent.OutputTuple,
      LoggerAuthorizedEvent.OutputObject
    >;
    LoggerAuthorized: TypedContractEvent<
      LoggerAuthorizedEvent.InputTuple,
      LoggerAuthorizedEvent.OutputTuple,
      LoggerAuthorizedEvent.OutputObject
    >;

    "LoggerRevoked(address)": TypedContractEvent<
      LoggerRevokedEvent.InputTuple,
      LoggerRevokedEvent.OutputTuple,
      LoggerRevokedEvent.OutputObject
    >;
    LoggerRevoked: TypedContractEvent<
      LoggerRevokedEvent.InputTuple,
      LoggerRevokedEvent.OutputTuple,
      LoggerRevokedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentAttested(uint256,bytes32,address,address,uint256,address,uint256,address,bytes32)": TypedContractEvent<
      PaymentAttestedEvent.InputTuple,
      PaymentAttestedEvent.OutputTuple,
      PaymentAttestedEvent.OutputObject
    >;
    PaymentAttested: TypedContractEvent<
      PaymentAttestedEvent.InputTuple,
      PaymentAttestedEvent.OutputTuple,
      PaymentAttestedEvent.OutputObject
    >;
  };
}
