/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PolicyEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activatePolicy"
      | "addApprovedRecipient"
      | "approvedRecipients"
      | "authorizeCaller"
      | "authorizedCallers"
      | "checkAndRecordSpend"
      | "configurePolicy"
      | "deactivatePolicy"
      | "getPolicy"
      | "owner"
      | "policies"
      | "removeApprovedRecipient"
      | "renounceOwnership"
      | "revokeCaller"
      | "simulateCheck"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CallerAuthorized"
      | "OwnershipTransferred"
      | "PolicyActivated"
      | "PolicyConfigured"
      | "PolicyDeactivated"
      | "PolicyViolation"
      | "RecipientApproved"
      | "RecipientRevoked"
      | "SpendRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activatePolicy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addApprovedRecipient",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approvedRecipients",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeCaller",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedCallers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkAndRecordSpend",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "configurePolicy",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivatePolicy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPolicy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "policies",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeApprovedRecipient",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCaller",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "simulateCheck",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "activatePolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addApprovedRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvedRecipients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedCallers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkAndRecordSpend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configurePolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivatePolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPolicy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "policies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeApprovedRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "simulateCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CallerAuthorizedEvent {
  export type InputTuple = [caller: AddressLike];
  export type OutputTuple = [caller: string];
  export interface OutputObject {
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyActivatedEvent {
  export type InputTuple = [business: AddressLike];
  export type OutputTuple = [business: string];
  export interface OutputObject {
    business: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyConfiguredEvent {
  export type InputTuple = [
    business: AddressLike,
    dailyLimit: BigNumberish,
    maxSingleTx: BigNumberish,
    minSingleTx: BigNumberish,
    requiresApprovedRecipients: boolean
  ];
  export type OutputTuple = [
    business: string,
    dailyLimit: bigint,
    maxSingleTx: bigint,
    minSingleTx: bigint,
    requiresApprovedRecipients: boolean
  ];
  export interface OutputObject {
    business: string;
    dailyLimit: bigint;
    maxSingleTx: bigint;
    minSingleTx: bigint;
    requiresApprovedRecipients: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyDeactivatedEvent {
  export type InputTuple = [business: AddressLike];
  export type OutputTuple = [business: string];
  export interface OutputObject {
    business: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyViolationEvent {
  export type InputTuple = [
    business: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    business: string,
    recipient: string,
    amount: bigint,
    reason: string
  ];
  export interface OutputObject {
    business: string;
    recipient: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecipientApprovedEvent {
  export type InputTuple = [business: AddressLike, recipient: AddressLike];
  export type OutputTuple = [business: string, recipient: string];
  export interface OutputObject {
    business: string;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecipientRevokedEvent {
  export type InputTuple = [business: AddressLike, recipient: AddressLike];
  export type OutputTuple = [business: string, recipient: string];
  export interface OutputObject {
    business: string;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SpendRecordedEvent {
  export type InputTuple = [
    business: AddressLike,
    amount: BigNumberish,
    dailyTotal: BigNumberish,
    dailyLimit: BigNumberish
  ];
  export type OutputTuple = [
    business: string,
    amount: bigint,
    dailyTotal: bigint,
    dailyLimit: bigint
  ];
  export interface OutputObject {
    business: string;
    amount: bigint;
    dailyTotal: bigint;
    dailyLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PolicyEngine extends BaseContract {
  connect(runner?: ContractRunner | null): PolicyEngine;
  waitForDeployment(): Promise<this>;

  interface: PolicyEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activatePolicy: TypedContractMethod<
    [business: AddressLike],
    [void],
    "nonpayable"
  >;

  addApprovedRecipient: TypedContractMethod<
    [business: AddressLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  approvedRecipients: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  authorizeCaller: TypedContractMethod<
    [caller: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedCallers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  checkAndRecordSpend: TypedContractMethod<
    [business: AddressLike, recipient: AddressLike, amount: BigNumberish],
    [[boolean, string] & { approved: boolean; reason: string }],
    "nonpayable"
  >;

  configurePolicy: TypedContractMethod<
    [
      business: AddressLike,
      dailyLimit: BigNumberish,
      maxSingleTx: BigNumberish,
      minSingleTx: BigNumberish,
      requiresApprovedRecipients: boolean
    ],
    [void],
    "nonpayable"
  >;

  deactivatePolicy: TypedContractMethod<
    [business: AddressLike],
    [void],
    "nonpayable"
  >;

  getPolicy: TypedContractMethod<
    [business: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean, boolean, bigint] & {
        dailyLimit: bigint;
        maxSingleTx: bigint;
        minSingleTx: bigint;
        dailySpent: bigint;
        active: boolean;
        requiresApprovedRecipients: boolean;
        remainingToday: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  policies: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, boolean] & {
        dailyLimit: bigint;
        maxSingleTx: bigint;
        minSingleTx: bigint;
        dailySpent: bigint;
        lastResetDay: bigint;
        active: boolean;
        requiresApprovedRecipients: boolean;
      }
    ],
    "view"
  >;

  removeApprovedRecipient: TypedContractMethod<
    [business: AddressLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeCaller: TypedContractMethod<
    [caller: AddressLike],
    [void],
    "nonpayable"
  >;

  simulateCheck: TypedContractMethod<
    [business: AddressLike, recipient: AddressLike, amount: BigNumberish],
    [
      [boolean, string, bigint] & {
        approved: boolean;
        reason: string;
        remainingDailyAllowance: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activatePolicy"
  ): TypedContractMethod<[business: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addApprovedRecipient"
  ): TypedContractMethod<
    [business: AddressLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approvedRecipients"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "authorizeCaller"
  ): TypedContractMethod<[caller: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedCallers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkAndRecordSpend"
  ): TypedContractMethod<
    [business: AddressLike, recipient: AddressLike, amount: BigNumberish],
    [[boolean, string] & { approved: boolean; reason: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "configurePolicy"
  ): TypedContractMethod<
    [
      business: AddressLike,
      dailyLimit: BigNumberish,
      maxSingleTx: BigNumberish,
      minSingleTx: BigNumberish,
      requiresApprovedRecipients: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivatePolicy"
  ): TypedContractMethod<[business: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPolicy"
  ): TypedContractMethod<
    [business: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean, boolean, bigint] & {
        dailyLimit: bigint;
        maxSingleTx: bigint;
        minSingleTx: bigint;
        dailySpent: bigint;
        active: boolean;
        requiresApprovedRecipients: boolean;
        remainingToday: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policies"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, boolean] & {
        dailyLimit: bigint;
        maxSingleTx: bigint;
        minSingleTx: bigint;
        dailySpent: bigint;
        lastResetDay: bigint;
        active: boolean;
        requiresApprovedRecipients: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeApprovedRecipient"
  ): TypedContractMethod<
    [business: AddressLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeCaller"
  ): TypedContractMethod<[caller: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "simulateCheck"
  ): TypedContractMethod<
    [business: AddressLike, recipient: AddressLike, amount: BigNumberish],
    [
      [boolean, string, bigint] & {
        approved: boolean;
        reason: string;
        remainingDailyAllowance: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CallerAuthorized"
  ): TypedContractEvent<
    CallerAuthorizedEvent.InputTuple,
    CallerAuthorizedEvent.OutputTuple,
    CallerAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PolicyActivated"
  ): TypedContractEvent<
    PolicyActivatedEvent.InputTuple,
    PolicyActivatedEvent.OutputTuple,
    PolicyActivatedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyConfigured"
  ): TypedContractEvent<
    PolicyConfiguredEvent.InputTuple,
    PolicyConfiguredEvent.OutputTuple,
    PolicyConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "PolicyDeactivated"
  ): TypedContractEvent<
    PolicyDeactivatedEvent.InputTuple,
    PolicyDeactivatedEvent.OutputTuple,
    PolicyDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyViolation"
  ): TypedContractEvent<
    PolicyViolationEvent.InputTuple,
    PolicyViolationEvent.OutputTuple,
    PolicyViolationEvent.OutputObject
  >;
  getEvent(
    key: "RecipientApproved"
  ): TypedContractEvent<
    RecipientApprovedEvent.InputTuple,
    RecipientApprovedEvent.OutputTuple,
    RecipientApprovedEvent.OutputObject
  >;
  getEvent(
    key: "RecipientRevoked"
  ): TypedContractEvent<
    RecipientRevokedEvent.InputTuple,
    RecipientRevokedEvent.OutputTuple,
    RecipientRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SpendRecorded"
  ): TypedContractEvent<
    SpendRecordedEvent.InputTuple,
    SpendRecordedEvent.OutputTuple,
    SpendRecordedEvent.OutputObject
  >;

  filters: {
    "CallerAuthorized(address)": TypedContractEvent<
      CallerAuthorizedEvent.InputTuple,
      CallerAuthorizedEvent.OutputTuple,
      CallerAuthorizedEvent.OutputObject
    >;
    CallerAuthorized: TypedContractEvent<
      CallerAuthorizedEvent.InputTuple,
      CallerAuthorizedEvent.OutputTuple,
      CallerAuthorizedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PolicyActivated(address)": TypedContractEvent<
      PolicyActivatedEvent.InputTuple,
      PolicyActivatedEvent.OutputTuple,
      PolicyActivatedEvent.OutputObject
    >;
    PolicyActivated: TypedContractEvent<
      PolicyActivatedEvent.InputTuple,
      PolicyActivatedEvent.OutputTuple,
      PolicyActivatedEvent.OutputObject
    >;

    "PolicyConfigured(address,uint256,uint256,uint256,bool)": TypedContractEvent<
      PolicyConfiguredEvent.InputTuple,
      PolicyConfiguredEvent.OutputTuple,
      PolicyConfiguredEvent.OutputObject
    >;
    PolicyConfigured: TypedContractEvent<
      PolicyConfiguredEvent.InputTuple,
      PolicyConfiguredEvent.OutputTuple,
      PolicyConfiguredEvent.OutputObject
    >;

    "PolicyDeactivated(address)": TypedContractEvent<
      PolicyDeactivatedEvent.InputTuple,
      PolicyDeactivatedEvent.OutputTuple,
      PolicyDeactivatedEvent.OutputObject
    >;
    PolicyDeactivated: TypedContractEvent<
      PolicyDeactivatedEvent.InputTuple,
      PolicyDeactivatedEvent.OutputTuple,
      PolicyDeactivatedEvent.OutputObject
    >;

    "PolicyViolation(address,address,uint256,string)": TypedContractEvent<
      PolicyViolationEvent.InputTuple,
      PolicyViolationEvent.OutputTuple,
      PolicyViolationEvent.OutputObject
    >;
    PolicyViolation: TypedContractEvent<
      PolicyViolationEvent.InputTuple,
      PolicyViolationEvent.OutputTuple,
      PolicyViolationEvent.OutputObject
    >;

    "RecipientApproved(address,address)": TypedContractEvent<
      RecipientApprovedEvent.InputTuple,
      RecipientApprovedEvent.OutputTuple,
      RecipientApprovedEvent.OutputObject
    >;
    RecipientApproved: TypedContractEvent<
      RecipientApprovedEvent.InputTuple,
      RecipientApprovedEvent.OutputTuple,
      RecipientApprovedEvent.OutputObject
    >;

    "RecipientRevoked(address,address)": TypedContractEvent<
      RecipientRevokedEvent.InputTuple,
      RecipientRevokedEvent.OutputTuple,
      RecipientRevokedEvent.OutputObject
    >;
    RecipientRevoked: TypedContractEvent<
      RecipientRevokedEvent.InputTuple,
      RecipientRevokedEvent.OutputTuple,
      RecipientRevokedEvent.OutputObject
    >;

    "SpendRecorded(address,uint256,uint256,uint256)": TypedContractEvent<
      SpendRecordedEvent.InputTuple,
      SpendRecordedEvent.OutputTuple,
      SpendRecordedEvent.OutputObject
    >;
    SpendRecorded: TypedContractEvent<
      SpendRecordedEvent.InputTuple,
      SpendRecordedEvent.OutputTuple,
      SpendRecordedEvent.OutputObject
    >;
  };
}
