/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAttestationLogger,
  IAttestationLoggerInterface,
} from "../../../contracts/PaymentOrchestrator.sol/IAttestationLogger";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "paymentId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "action",
        type: "string",
      },
      {
        internalType: "bytes32",
        name: "inputHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "outputHash",
        type: "bytes32",
      },
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    name: "logAgentAction",
    outputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "paymentId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "business",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "agentId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "stateHash",
        type: "bytes32",
      },
    ],
    name: "logPayment",
    outputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAttestationLogger__factory {
  static readonly abi = _abi;
  static createInterface(): IAttestationLoggerInterface {
    return new Interface(_abi) as IAttestationLoggerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAttestationLogger {
    return new Contract(address, _abi, runner) as unknown as IAttestationLogger;
  }
}
