/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPolicyEngine,
  IPolicyEngineInterface,
} from "../../../contracts/PaymentOrchestrator.sol/IPolicyEngine";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "business",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "checkAndRecordSpend",
    outputs: [
      {
        internalType: "bool",
        name: "approved",
        type: "bool",
      },
      {
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPolicyEngine__factory {
  static readonly abi = _abi;
  static createInterface(): IPolicyEngineInterface {
    return new Interface(_abi) as IPolicyEngineInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPolicyEngine {
    return new Contract(address, _abi, runner) as unknown as IPolicyEngine;
  }
}
