/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IMentoBrokerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAmountIn"
      | "getAmountOut"
      | "getExchangeProviders"
      | "swapIn"
      | "swapOut"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAmountIn",
    values: [AddressLike, BytesLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAmountOut",
    values: [AddressLike, BytesLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getExchangeProviders",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapIn",
    values: [
      AddressLike,
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapOut",
    values: [
      AddressLike,
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAmountIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAmountOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExchangeProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapIn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "swapOut", data: BytesLike): Result;
}

export interface IMentoBroker extends BaseContract {
  connect(runner?: ContractRunner | null): IMentoBroker;
  waitForDeployment(): Promise<this>;

  interface: IMentoBrokerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAmountIn: TypedContractMethod<
    [
      exchangeProvider: AddressLike,
      exchangeId: BytesLike,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountOut: BigNumberish
    ],
    [bigint],
    "view"
  >;

  getAmountOut: TypedContractMethod<
    [
      exchangeProvider: AddressLike,
      exchangeId: BytesLike,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish
    ],
    [bigint],
    "view"
  >;

  getExchangeProviders: TypedContractMethod<[], [string[]], "view">;

  swapIn: TypedContractMethod<
    [
      exchangeProvider: AddressLike,
      exchangeId: BytesLike,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      amountOutMin: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  swapOut: TypedContractMethod<
    [
      exchangeProvider: AddressLike,
      exchangeId: BytesLike,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountOut: BigNumberish,
      amountInMax: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAmountIn"
  ): TypedContractMethod<
    [
      exchangeProvider: AddressLike,
      exchangeId: BytesLike,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountOut: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAmountOut"
  ): TypedContractMethod<
    [
      exchangeProvider: AddressLike,
      exchangeId: BytesLike,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getExchangeProviders"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "swapIn"
  ): TypedContractMethod<
    [
      exchangeProvider: AddressLike,
      exchangeId: BytesLike,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountIn: BigNumberish,
      amountOutMin: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapOut"
  ): TypedContractMethod<
    [
      exchangeProvider: AddressLike,
      exchangeId: BytesLike,
      tokenIn: AddressLike,
      tokenOut: AddressLike,
      amountOut: BigNumberish,
      amountInMax: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
