/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc8004Sol from "./IERC8004.sol";
export type { ierc8004Sol };
export type { IMentoBroker } from "./IMentoBroker";
